'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Width1() As Integer
            Get
                Return CType(Me("Width1"),Integer)
            End Get
            Set
                Me("Width1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Height1() As Integer
            Get
                Return CType(Me("Height1"),Integer)
            End Get
            Set
                Me("Height1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Location1() As Global.System.Drawing.Point
            Get
                Return CType(Me("Location1"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Location1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Size1() As Global.System.Drawing.Size
            Get
                Return CType(Me("Size1"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Size1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Left1() As Integer
            Get
                Return CType(Me("Left1"),Integer)
            End Get
            Set
                Me("Left1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Top1() As Integer
            Get
                Return CType(Me("Top1"),Integer)
            End Get
            Set
                Me("Top1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Valorant1() As Boolean
            Get
                Return CType(Me("Valorant1"),Boolean)
            End Get
            Set
                Me("Valorant1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Fadeint1() As Integer
            Get
                Return CType(Me("Fadeint1"),Integer)
            End Get
            Set
                Me("Fadeint1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Markersize1() As Integer
            Get
                Return CType(Me("Markersize1"),Integer)
            End Get
            Set
                Me("Markersize1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Variation1() As Integer
            Get
                Return CType(Me("Variation1"),Integer)
            End Get
            Set
                Me("Variation1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Fadetime1() As Integer
            Get
                Return CType(Me("Fadetime1"),Integer)
            End Get
            Set
                Me("Fadetime1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Delay1() As Integer
            Get
                Return CType(Me("Delay1"),Integer)
            End Get
            Set
                Me("Delay1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Pixelcolor1() As Global.System.Drawing.Color
            Get
                Return CType(Me("Pixelcolor1"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Pixelcolor1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Alarmsound1() As Boolean
            Get
                Return CType(Me("Alarmsound1"),Boolean)
            End Get
            Set
                Me("Alarmsound1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Maptracker1() As Boolean
            Get
                Return CType(Me("Maptracker1"),Boolean)
            End Get
            Set
                Me("Maptracker1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Bombtimer1() As Boolean
            Get
                Return CType(Me("Bombtimer1"),Boolean)
            End Get
            Set
                Me("Bombtimer1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Bombcoordinatesx1() As Integer
            Get
                Return CType(Me("Bombcoordinatesx1"),Integer)
            End Get
            Set
                Me("Bombcoordinatesx1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Bombcoordinatesy1() As Integer
            Get
                Return CType(Me("Bombcoordinatesy1"),Integer)
            End Get
            Set
                Me("Bombcoordinatesy1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Width2() As Integer
            Get
                Return CType(Me("Width2"),Integer)
            End Get
            Set
                Me("Width2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Height2() As Integer
            Get
                Return CType(Me("Height2"),Integer)
            End Get
            Set
                Me("Height2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Location2() As Global.System.Drawing.Point
            Get
                Return CType(Me("Location2"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Location2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Size2() As Global.System.Drawing.Size
            Get
                Return CType(Me("Size2"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Size2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Left2() As Integer
            Get
                Return CType(Me("Left2"),Integer)
            End Get
            Set
                Me("Left2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Top2() As Integer
            Get
                Return CType(Me("Top2"),Integer)
            End Get
            Set
                Me("Top2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Valorant2() As Boolean
            Get
                Return CType(Me("Valorant2"),Boolean)
            End Get
            Set
                Me("Valorant2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Fadeint2() As Integer
            Get
                Return CType(Me("Fadeint2"),Integer)
            End Get
            Set
                Me("Fadeint2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Markersize2() As Integer
            Get
                Return CType(Me("Markersize2"),Integer)
            End Get
            Set
                Me("Markersize2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Variation2() As Integer
            Get
                Return CType(Me("Variation2"),Integer)
            End Get
            Set
                Me("Variation2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Fadetime2() As Integer
            Get
                Return CType(Me("Fadetime2"),Integer)
            End Get
            Set
                Me("Fadetime2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Delay2() As Integer
            Get
                Return CType(Me("Delay2"),Integer)
            End Get
            Set
                Me("Delay2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Pixelcolor2() As Global.System.Drawing.Color
            Get
                Return CType(Me("Pixelcolor2"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Pixelcolor2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Alarmsound2() As Boolean
            Get
                Return CType(Me("Alarmsound2"),Boolean)
            End Get
            Set
                Me("Alarmsound2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Maptracker2() As Boolean
            Get
                Return CType(Me("Maptracker2"),Boolean)
            End Get
            Set
                Me("Maptracker2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Alarm2() As Boolean
            Get
                Return CType(Me("Alarm2"),Boolean)
            End Get
            Set
                Me("Alarm2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Multitarget2() As Boolean
            Get
                Return CType(Me("Multitarget2"),Boolean)
            End Get
            Set
                Me("Multitarget2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Precise2() As Integer
            Get
                Return CType(Me("Precise2"),Integer)
            End Get
            Set
                Me("Precise2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Saved() As String
            Get
                Return CType(Me("Saved"),String)
            End Get
            Set
                Me("Saved") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Bombtimer2() As Boolean
            Get
                Return CType(Me("Bombtimer2"),Boolean)
            End Get
            Set
                Me("Bombtimer2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Bomdefusetime() As Integer
            Get
                Return CType(Me("Bomdefusetime"),Integer)
            End Get
            Set
                Me("Bomdefusetime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Bombexplodetime() As Integer
            Get
                Return CType(Me("Bombexplodetime"),Integer)
            End Get
            Set
                Me("Bombexplodetime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Bombvariation() As Integer
            Get
                Return CType(Me("Bombvariation"),Integer)
            End Get
            Set
                Me("Bombvariation") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.iBaseTools.My.MySettings
            Get
                Return Global.iBaseTools.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
